# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b181d1b9-f53a-4a3a-9bd1-392b7d47d6cb";
    fsType = "btrfs";
    options = [ "subvol=root" ];
  };

  boot.initrd.luks.devices."cryptroot".device =
    "/dev/disk/by-uuid/2f4e28a5-36d1-43a0-9005-101e93fddd7c";

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/b181d1b9-f53a-4a3a-9bd1-392b7d47d6cb";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/b181d1b9-f53a-4a3a-9bd1-392b7d47d6cb";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/b181d1b9-f53a-4a3a-9bd1-392b7d47d6cb";
    fsType = "btrfs";
    options = [ "subvol=var/log" ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/b181d1b9-f53a-4a3a-9bd1-392b7d47d6cb";
    fsType = "btrfs";
    options = [ "subvol=swap" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/096A-013F";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  # hardware.cpu.intel.npu.enable = true; TODO https://github.com/NixOS/nixpkgs/issues/470638
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
