version: 2
updates:
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "private"
      - dependency-name: "frappe"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
