version: 2
updates:
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 17 * * *"
      timezone: "Europe/Amsterdam"
    ignore:
      - dependency-name: "private"
      - dependency-name: "frappe"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
