# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a399f6cf-e74d-40dd-9668-6e6dd24d5bcd";
    fsType = "btrfs";
    options = [ "subvol=root" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/a399f6cf-e74d-40dd-9668-6e6dd24d5bcd";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/a399f6cf-e74d-40dd-9668-6e6dd24d5bcd";
    fsType = "btrfs";
    options = [ "subvol=var/log" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/a399f6cf-e74d-40dd-9668-6e6dd24d5bcd";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/btr_pool" = {
    device = "/dev/disk/by-uuid/a399f6cf-e74d-40dd-9668-6e6dd24d5bcd";
    fsType = "btrfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/47A2-2CEF";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
